name: "pyannote_diarization"
backend: "python"
max_batch_size: 1
dynamic_batching: {
    default_queue_policy: {
        timeout_action: REJECT
        default_timeout_microseconds: 900000000
    }
}

input [
    {
        name: "audio_input"
        data_type: TYPE_FP32
        dims: [-1]
    },
    {
        name: "num_speakers_input"
        data_type: TYPE_INT32
        dims: [-1]
        optional: true
    },
    {
        name: "min_speakers_input"
        data_type: TYPE_INT32
        dims: [-1]
        optional: true
    },
    {
        name: "max_speakers_input"
        data_type: TYPE_INT32
        dims: [-1]
        optional: true
    },
    {
        name: "return_embeddings_input"
        data_type: TYPE_BOOL
        dims: [-1]
        optional: true
    },
    {
        name: "request_id_input"
        data_type: TYPE_STRING
        dims: [-1]
        optional: true
  }

]
output [
    {
        name: "diarization_output"
        data_type: TYPE_STRING
        dims: [-1]
    }
]
instance_group [{ kind: KIND_GPU , count: 15 }]
